SELECT ' CREATE SEQUENCE ' || SEQUENCE_NAME || ' INCREMENT BY ' ||
       　　INCREMENT_BY || ' START WITH ' || LAST_NUMBER || ' MAXVALUE ' ||
       　　MAX_VALUE || '   CACHE ' || CACHE_SIZE || ' ORDER NOCYCLE ;' 　　FROM user_SEQUENCES;
