SELECT
	A.CONSTRAINT_NAME,
	A.TABLE_NAME,
	A.COLUMN_NAME,
	B.CONSTRAINT_TYPE 
FROM
	USER_CONS_COLUMNS A,
	USER_CONSTRAINTS B 
WHERE
	A.CONSTRAINT_NAME = B.CONSTRAINT_NAME 
	AND a.constraint_name LIKE '%约束名称%';

